###
# * Backend Configuration (Defaults)
#
# - Sane defaults for native deployment. These are the fallback values when not defined in `user.toml`.
#
# - Many settings are for ADVANCED USE and should generally not be changed. For most users, we recommend
#   copying the `user.example.toml` file, renaming it to `user.toml` and modifying it to suit your needs.
#
# - Please note the defaults in `user.example.toml` are geared towards basic deployment with DOCKER. If you
#   plan to deploy the app natively, you are likely an ADVANCED USER, and should copy this file instead as a
#   starting point for the `user.toml` configuration. All possible config values are documented here.
###

[DJANGO]
# Core Django Configuration
# SECURITY WARNING: Never enable DEBUG in production!
DEBUG = false
# SECURITY WARNING: Change these and keep them SECRET for production! -- https://djecrety.ir/
SECRET_KEY = "secret-key"
SALT_KEY = "salt-key"
# Any request not matching one of these hosts will be rejected. Below are some example rules:
# - Allow all hosts: ["*"]
# - Allow your domain and/or subdomain: ["mydomain.com", "sub.mydomain.com"]
# - Allow your domain and any subdomain: ["mydomain.com", ".mydomain.com"]
# - "django-api" should ALWAYS be included in these rules if deploying with docker!
ALLOWED_HOSTS = ["django-api", "localhost", "127.0.0.1"]
# Origins that are authorized to make cross-site HTTP requests (requires protocol i.e. http/https!)
# Allow your own address/domain(s) and any outside domains you want to be able to access the API
CORS_ALLOWED_ORIGINS = ["http://django-api", "http://localhost", "http://127.0.0.1", "https://mpcautofill.github.io"]
# Only these addresses/domains can use the Django Admin login form (requires protocol i.e. http/https!)
# CAUTION: You should probably only allow your address/domain here
CSRF_TRUSTED_ORIGINS = ["http://django-api", "http://localhost", "http://127.0.0.1"]
# You should probably enable these when deploying a public instance
SESSION_COOKIE_SECURE = false
CSRF_COOKIE_SECURE = false
# Whether to prepend "www." subdomain to URLs when missing
PREPEND_WWW = false
# Localization settings
LANG_CODE = "en-us"
TIME_ZONE = "America/Chicago"
USE_I18N = true
USE_L10N = true
USE_TZ = true

[SITE]
# Cosmetic site details
NAME = "MPC Autofill"
DESCRIPTION = "A crowdsourced card image database."
GAME = "MTG"
DISCORD = "https://nux.cam/discord"
REDDIT = "https://www.reddit.com/r/mpcproxies/"

[CARDPICKER]
# Cardpicker Configuration
# Path to and image name of cardback to order first in the UI (if it exists)
DEFAULT_CARDBACK_FOLDER_PATH = "Chilli_Axe's MTG Renders / 12. Cardbacks"
DEFAULT_CARDBACK_IMAGE_NAME = "Black Lotus"

[DATABASE]
# Postgres Database, create username/pass for security
ENGINE = "django.db.backends.postgresql"
NAME = "mpcautofill"
USER = "mpcautofill"
PASSWORD = "mpcautofill"
HOST = "localhost"
PORT = "5432"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

[ELASTICSEARCH]
# Elasticsearch Configuration
HOST = "localhost"
PORT = 9200
# Elasticsearchg authentication (ADVANCED)
USER = ""
PASSWORD = ""

[UNFOLD]
# Unfold Admin Panel Configuration
SITE_TITLE = "MPC Autofill Admin"
SITE_HEADER = "Making better images!"

[EMAIL]
# Email Configuration (ADVANCED): Defaults are oriented towards Gmail
BACKEND = "django.core.mail.backends.smtp.EmailBackend"
HOST = "smtp.gmail.com"
# Gmail address and "App Password" generated by Google (must enable 2FA)
HOST_USER = ""
HOST_PASSWORD = ""
# Port, TLS, SSL related settings are only applicable for very advanced users
PORT = 587
USE_TLS = true
USE_SSL = false
SSL_CERTFILE = ""
SSL_KEYFILE = ""
# Treated as the official site address, publicly viewable in production
PUBLIC_ADDRESS = "webmaster@site.address"
# Address format listed in the "From:" line for automated mail sent TO site users
NOREPLY_ADDRESS = "MPC Autofill <noreply@site.address>"
# Address format listed in the "From:" line for automated mail sent TO site admins for error reporting
SERVER_ADDRESS = "MPC Autofill Server <server@site.address>"
# Subject-line prefix for automated mail sent by the site
SUBJECT_PREFIX = "[MPC Autofill] "
# Use local time zone if True, otherwise UTC
USE_LOCALTIME = false
# The directory used by the email backend to store output files
FILE_PATH = ""
# Specifies a timeout in seconds for blocking operations like the connection attempt (0 = None)
TIMEOUT = 90
# A list of administrators who receive error notifications (each item contains a name and email address)
ADMINS = [ [ "admin", "webmaster@site.address" ] ]

[ANALYTICS]
# Analytics integrations (ADVANCED)
GOOGLE_TAG = ""

[SENTRY]
# Sentry integration (ADVANCED)
ENABLED = false
# Data Source Name where events should be sent (URL provided by Sentry)
DSN = ""
# If you wish to associate users with errors (assuming you are using django.contrib.auth)
# you may enable sending PII data.
SEND_DEFAULT_PII = true
# Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
# We recommend adjusting this value in production.
TRACES_SAMPLE_RATE = 1.0
# Set profiles_sample_rate to 1.0 to profile 100% of sampled transactions.
# We recommend adjusting this value in production.
PROFILES_SAMPLE_RATE = 1.0
