# Generated by Django 4.2.21 on 2025-08-10 16:33

from django.db import migrations, models
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cardpicker', '0043_auto_20250529_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', encrypted_fields.fields.EncryptedTextField()),
            ],
            options={
                'verbose_name': 'Site Secret',
                'verbose_name_plural': 'Site Secrets',
            },
        ),
        migrations.AddField(
            model_name='source',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='Paused'),
        ),
        migrations.AddField(
            model_name='source',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
