# Generated by Django 4.2.21 on 2025-08-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpicker', '0044_sitesecret_source_is_paused_source_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='ordinal',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
